- name: Install Java 11 and Jenkins
  hosts: test
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update the apt cache (Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Java 11 (Debian-based systems)
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Jenkins repository key (Debian-based systems)
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Jenkins repository (Debian-based systems)
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Jenkins (Debian-based systems)
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == "Debian"
